# should run on all branches on push
name: test
on:  
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./test.sh --is-ci
